import {
    PROOF_OF_IDENTITY_ACTION_CID,
    PROOF_OF_MEMBERSHIP_ACTION_CID,
    IDENTITY_PROOF_SIGNER_PKP_PUBLIC_KEY,
    IDENTITY_PROOF_SIGNER_PKP_ADDRESS,
    MEMBERSHIP_PROOF_SIGNER_PKP_PUBLIC_KEY,
    MEMBERSHIP_PROOF_SIGNER_PKP_ADDRESS,
  } from "../config/constants";

export default class LitPrivacyConstants {
  public static LIT_ACTIONS_CID = {
    PROOF_OF_IDENTITY: PROOF_OF_IDENTITY_ACTION_CID,
    PROOF_OF_MEMBERSHIP: PROOF_OF_MEMBERSHIP_ACTION_CID,
  };
  public static IDENTITY_PROOF_SIGNER_PKP = {
    PUBLIC_KEY: IDENTITY_PROOF_SIGNER_PKP_PUBLIC_KEY,
    ADDRESS: IDENTITY_PROOF_SIGNER_PKP_ADDRESS,
  };
  public static MEMBERSHIP_PROOF_SIGNER_PKP = {
    PUBLIC_KEY: MEMBERSHIP_PROOF_SIGNER_PKP_PUBLIC_KEY,
    ADDRESS: MEMBERSHIP_PROOF_SIGNER_PKP_ADDRESS,
  };
}